import type { ScenarioOptions } from '../algorithm-step.types';

export interface TemplateVaultOptions {
  includeFastIO: boolean;
  indexing: '0-based' | '1-based';
  lazy: boolean;
  aggregate: 'sum' | 'min' | 'max';
}

export function generateCppTemplate(opts: TemplateVaultOptions): string {
  const isLazy = opts.lazy;
  const agg = opts.aggregate;
  const is1Based = opts.indexing === '1-based';

  let combineCode = 'return a + b;';
  let neutralCode = '0';
  if (agg === 'min') {
    combineCode = 'return std::min(a, b);';
    neutralCode = '1e18';
  } else if (agg === 'max') {
    combineCode = 'return std::max(a, b);';
    neutralCode = '-1e18';
  }

  const fastIoSnippet = opts.includeFastIO
    ? `    std::ios_base::sync_with_stdio(false);\n    std::cin.tie(NULL);\n`
    : '';

  return `// Competitive Programming C++20 Segment Tree Template (${is1Based ? '1-indexed' : '0-indexed'})
// Generated by Segment Tree Interactive Studio
#include <bits/stdc++.h>
using namespace std;

template<typename T = long long>
struct SegmentTree {
    int n;
    vector<T> tree;
    ${isLazy ? 'vector<T> lazy;' : ''}
    T NEUTRAL = ${neutralCode};

    T combine(T a, T b) {
        ${combineCode}
    }

    SegmentTree(int n) : n(n) {
        tree.assign(4 * n, ${neutralCode});
        ${isLazy ? 'lazy.assign(4 * n, 0);' : ''}
    }

    void build(const vector<T>& a, int node, int start, int end) {
        if (start == end) {
            tree[node] = a[start];
            return;
        }
        int mid = start + (end - start) / 2;
        build(a, 2 * node + 1, start, mid);
        build(a, 2 * node + 2, mid + 1, end);
        tree[node] = combine(tree[2 * node + 1], tree[2 * node + 2]);
    }

    ${
      isLazy
        ? `void push(int node, int start, int end) {
        if (lazy[node] == 0) return;
        tree[node] += lazy[node] * (end - start + 1);
        if (start != end) {
            lazy[2 * node + 1] += lazy[node];
            lazy[2 * node + 2] += lazy[node];
        }
        lazy[node] = 0;
    }\n`
        : ''
    }
    T query(int node, int start, int end, int l, int r) {
        ${isLazy ? 'push(node, start, end);\n        ' : ''}if (r < start || end < l) return NEUTRAL;
        if (l <= start && end <= r) return tree[node];
        int mid = start + (end - start) / 2;
        return combine(query(2 * node + 1, start, mid, l, r),
                       query(2 * node + 2, mid + 1, end, l, r));
    }

    ${
      isLazy
        ? `void updateRange(int node, int start, int end, int l, int r, T val) {
        push(node, start, end);
        if (r < start || end < l) return;
        if (l <= start && end <= r) {
            lazy[node] += val;
            push(node, start, end);
            return;
        }
        int mid = start + (end - start) / 2;
        updateRange(2 * node + 1, start, mid, l, r, val);
        updateRange(2 * node + 2, mid + 1, end, l, r, val);
        tree[node] = combine(tree[2 * node + 1], tree[2 * node + 2]);
    }`
        : `void updatePoint(int node, int start, int end, int idx, T val) {
        if (start == end) {
            tree[node] = val;
            return;
        }
        int mid = start + (end - start) / 2;
        if (idx <= mid) updatePoint(2 * node + 1, start, mid, idx, val);
        else updatePoint(2 * node + 2, mid + 1, end, idx, val);
        tree[node] = combine(tree[2 * node + 1], tree[2 * node + 2]);
    }`
    }
};

int main() {
${fastIoSnippet}    return 0;
}
`;
}

export function createVaultStore() {
  let includeFastIO = $state(true);
  let quizAnswerState = $state<{ selected: string | null; isCorrect: boolean | null }>({
    selected: null,
    isCorrect: null,
  });

  function getTemplateForOptions(scenario: ScenarioOptions): string {
    return generateCppTemplate({
      includeFastIO,
      indexing: scenario.indexing,
      lazy: scenario.lazy,
      aggregate: scenario.aggregate,
    });
  }

  function setFastIO(enabled: boolean) {
    includeFastIO = enabled;
  }

  function answerQuiz(selected: 'fullOverlap' | 'partialOverlap' | 'noOverlap', correct: string) {
    quizAnswerState = {
      selected,
      isCorrect: selected === correct,
    };
  }

  function resetQuiz() {
    quizAnswerState = { selected: null, isCorrect: null };
  }

  return {
    get includeFastIO() {
      return includeFastIO;
    },
    get quizAnswerState() {
      return quizAnswerState;
    },
    getTemplateForOptions,
    setFastIO,
    answerQuiz,
    resetQuiz,
  };
}

export type VaultStore = ReturnType<typeof createVaultStore>;
